name: Github Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Build
        run: yarn run build
        env:
          GATSBY_ENV: "prod"

      - name: Deploy
        run: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
